WIP: separate response body form database sturct
PuriPuriApplication/torimo-article-api pull request #11
Opened 2020-03-20 11:17 UTC by MSHR-Dec

## レビューよろしくお願いします🙏
entityとresponseを分離するPRです。

ひとまずPOSTで作成したArticleIDに関してのみResponseBodyにMappingするようにしているため `WIP` になっています。
​
## Refs: 関連ファイル
​
## Why: なぜこの変更をするのか
​
## What: 何をどう変更したのか
handler/responseにResponseBodyの構造体を定義して、article_handlerでレスポンスを返す時に、Insertの結果を作成したResponseBodyにMappingするようにした。
​
## Affected range: この変更によりどこが影響を受けるのか
​​
## Point: レビュアーは何を確認すればいいのか
​
## Other: その他

2020-03-20 11:37 UTC, noriyuki-shimizu reviewed
修正ありがとうございます！！

今回の作成処理の場合だとレスポンスは ID のみなのでここは、プレーンなレスポンスでいい気がしました！(struct 化しなくてもいいかもしれません)
レスポンスがオブジェクトの場合はレスポンスモデルを定義してあげる感じでいいと思います！

2020-03-20 11:37 UTC, noriyuki-shimizu commented on src/handler/response/article.go
> +	Id uint64 `json:"id""`
ダブルクォート一つ多い？

2020-03-20 11:37 UTC, noriyuki-shimizu commented on src/handler/response/article.go
> +func NewCreatedArticle(ai uint64) *CreatedArticle {
引数名は id でいい気がしましたがいかがでしょう？

2020-03-20 11:46 UTC, MSHR-Dec commented on src/handler/response/article.go
> +func NewCreatedArticle(ai uint64) *CreatedArticle {
ここの命名は悩んでたので `id` に修正しました！

2020-03-20 12:17 UTC, MSHR-Dec commented
> 修正ありがとうございます！！
> 
> 今回の作成処理の場合だとレスポンスは ID のみなのでここは、プレーンなレスポンスでいい気がしました！(struct 化しなくてもいいかもしれません)
> レスポンスがオブジェクトの場合はレスポンスモデルを定義してあげる感じでいいと思います！

GoでJsonを扱う時って構造体を定義するのが一般的かと考えているのですが、他の実装の仕方がある感じですか？

2020-03-22 01:35 UTC, MSHR-Dec commented
既存のアーキテクチャに沿ってResponseとEntityの処理を分割するように修正し、動作確認ができたので `WIP` 外しました。

2020-03-22 09:40 UTC, noriyuki-shimizu requested changes
たくさんの修正ありがとうございます！
ここまで作成するのは大変だったかと思われます。

ただ、パッケージ構成や処理の責務などに関してはもう少し話し合う必要があるかと思われます。
そのためペアプロか何かさせていただきたいです🙇‍♂️

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/domain/article_model/article.go
> +package article_model
domain/article_model ってことは記事以外のモデルが増えたときに domain/xxx_model って増えていく感じっすよね？
個人的には model のままがいいと思っています。
また、パッケージ名には複数単語を用いるのはシンプルな go ではよくないとされています。

https://micnncim.com/post/2019/12/11/go-naming-conventions/

今回の修正で言うと、article_model.article とのように同じ単語が２つ続いてしまうのはわかりにくい構成に繋がりかねません。
またパッケージ名は model のような少し抽象的な意味合いを持たせた命名にすることがいいと思います。

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/domain/article_repository/article-category.go
> +package article_repository
上記同件です。

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/domain/response_repository/category.go
> +package response_repository
このパッケージ名を見るとリクエストされたクライアントに、レポジトリを返すような役割のパッケージ名に見えるのですが、どのような意味を込めたかったのかとかありますでしょうか？

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/handler/article.go
> +	return c.JSON(http.StatusOK, ah.ResponseUsecase.CreateAll(articles))
ちょっとクリーンアーキテクチャの話にもなるのですが、データをクライアントに返すためのデータ変換処理は Presenter (プレゼンター) 層が担うものだと思います。
ユースケースと言うのはそのエンドポイントがどのような処理を実現してくれるのかを担う層です。

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/infrastructure/dataconvert/category.go
> +	for _, v := range category {
FYI: go-funk をモジュールに含めたので、そちらを使ってループを回すのもアリかと

https://github.com/thoas/go-funk

```go
	results := funk.Map(categories, func(category article_model.Category) response_model.ResponseCategory {
		return &response_model.ResponseCategory{
			ID:         v.ID,
			Name:       v.Name,
			CreateUser: v.CreateUser,
			IsDeleted:  v.IsDeleted,
		}
	}).([]*response_model.ResponseCategory)
```

変数名とかは一部変更しています。

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/infrastructure/dataconvert/shop.go
> +	return &response_model.ResponseShop{
ポインタで渡す意味はありますでしょうか？

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/infrastructure/dataconvert/user.go
> +	return &response_model.ResponseUser{
ここら辺も上記同様です

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/infrastructure/datastore/category.go
> +	var category []article_model.Category
保守性が高くなりますね👍
ありがとうございます！

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/interactor/response.go
> +			User:       ri.UserResponseRepository.Convert(&v.User),
convert は repository の責務ではないと思います

2020-03-22 09:40 UTC, noriyuki-shimizu commented on src/interactor/response.go
> +func (ri *ResponseInteractor) CreateAll(a []article_model.Article) *[]response_model.ResponseArticle {
CreateAll との命名だと、データが作成されるような意味として捉えてしまうと思います。
データが作成と言うのは、ファイルに新規作成される・DBの１レコードとして新規作成されるなどなど
本メソッドの処理を見ると、モデルをレスポンスモデルに変換しているように見受けられます。
そのため、Create と言うより Convert / Mapping など（他にも色々あるかもしれませんが）が意味としてあっているような気がします。

2020-03-22 09:42 UTC, noriyuki-shimizu commented on src/domain/article_model/article.go
> +package article_model
domain/article_model のような構成にしたい場合は、domain/model/articles/xxx.go のようなパッケージ構成がいいかと思われます。

2020-03-26 08:36 UTC, wataru3110 reviewed
清水さんのレビュー修正後また見ます！

2020-04-09 14:03 UTC, merged